theme: jekyll-theme-minimal
title: [Teaching Data Science & Statistics for Social Justice]
logo: /Figures/datasj1.png
description: [Tools and resources for teaching data science and statistics with a framing in social justice.]
url: https://annahaensch.github.io/
