theme: jekyll-theme-minimal
title: [Data Science & Social Justice]
logo: /Figures/data_art.png
description: [Tools for teaching data science and statistics for social justice.]
url: https://annahaensch.github.io/
